name: Build package
on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true

jobs:
  build:
    name: Build package (${{ inputs.os }})
    runs-on: ${{ inputs.os }}
    steps:
      - name: Extract Version Name
        id: extract_name
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            if (context.payload.ref.startsWith('refs/tags/')) {
              return context.payload.ref.replace(/refs\/tags\/v/, '');
            }
            return 'dev';
      - name: Set version
        run: echo ${{ steps.extract_name.outputs.result }} > assets/appversion
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Setup (${{ inputs.os }})
        if: inputs.os == 'ubuntu-latest'
        run: sudo apt-get install golang gcc libgl1-mesa-dev xorg-dev
      - name: Install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: fyne package --appID com.rikudousage.large_csv_reader
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            LargeCsvReader.app
            LargeCsvReader.tar.xz
            LargeCsvReader.exe
          name: ${{ inputs.os }}
