name: Build project
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  package:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: Package (${{ matrix.os }})
    uses: ./.github/workflows/build-package.yaml
    with:
      os: ${{ matrix.os }}

  package_linux:
    name: Package (Linux)
    uses: ./.github/workflows/build-package.yaml
    with:
      os: ubuntu-latest

  build_rpm:
    name: Build RPM
    needs:
      - package_linux
    runs-on: ubuntu-latest
    env:
      APP_VERSION: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install rpm
        run: sudo apt-get -y install rpm
      - name: Download built
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest
      - name: Create sources directory
        run: mkdir -p spec/SOURCES
      - name: Move file
        run: mv LargeCsvReader.tar.xz spec/SOURCES
      - name: Build RPM
        run: rpmbuild -ba --define "_topdir $(pwd)/spec" --define "app_version $APP_VERSION" spec/LargeCsvReader.spec
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: spec/RPMS/x86_64/LargeCsvReader-$APP_VERSION-1.fc40.x86_64.rpm
          name: rpm
