name: Build project
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  package_macos:
    name: Package (macos-latest)
    uses: ./.github/workflows/build-package.yaml
    with:
      os: macos-latest

  package_windows:
    name: Package (windows-latest)
    uses: ./.github/workflows/build-package.yaml
    with:
      os: windows-latest

  package_linux:
    name: Package (ubuntu-latest)
    uses: ./.github/workflows/build-package.yaml
    with:
      os: ubuntu-latest

  build_rpm:
    name: Build RPM
    needs:
      - package_linux
    runs-on: ubuntu-latest
    env:
      APP_VERSION: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install rpm
        run: sudo apt-get -y install rpm
      - name: Download built
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest
      - name: Create sources directory
        run: mkdir -p rpm/SOURCES
      - name: Move file
        run: mv LargeCsvReader.tar.xz rpm/SOURCES
      - name: Build RPM
        run: rpmbuild -ba --define "_topdir $(pwd)/rpm" --define "app_version $APP_VERSION" rpm/LargeCsvReader.spec
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: rpm/RPMS/x86_64/LargeCsvReader-${{ env.APP_VERSION }}-1.x86_64.rpm
          name: rpm
  build_win_installer:
    name: Build Windows installer
    needs:
      - package_windows
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Download built
        uses: actions/download-artifact@v4
        with:
          name: windows-latest
      - name: Move file
        run: mv LargeCsvReader.exe windows
      - name: Create Windows setup
        run: iscc setup.iss
        working-directory: windows
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: windows/LargeCsvReaderSetup.exe
          name: win_installer
