name: Build package
on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true

jobs:
  build:
    name: Build package (${{ inputs.os }})
    runs-on: ${{ inputs.os }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Setup (ubuntu)
        if: inputs.os == 'ubuntu-latest'
        run: sudo apt-get install golang gcc libgl1-mesa-dev xorg-dev
      - name: Install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: fyne package --appID com.rikudousage.large_csv_reader
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            LargeCsvReader.app
            LargeCsvReader.tar.xz
            LargeCsvReader.exe
          name: ${{ inputs.os }}
